//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FancyRidesApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FancyRidesEntities : DbContext
    {
        public FancyRidesEntities()
            : base("name=FancyRidesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FancyRidesRecord> FancyRidesRecords { get; set; }
        public virtual DbSet<TypesOfCar> TypesOfCars { get; set; }
    }
}
